valor = input("Digite algo: ")
print("o Valor digitado é do tipo {}".format(type(valor)))
print("É númerico? {}".format(valor.isnumeric()))
print("É alfa númerico? {}".format(valor.isalnum()))
print("É maiusculo? {}".format(valor.isupper()))
